# Demonstração KNN com Flor Iris

Base de Dados Iris

In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Carregar o conjunto de dados Iris
iris = load_iris()

print("Amostra de entrada")
print(iris.data)
print()
print("Rótulo de Classe")
print(iris.target)
print()
print("Nome das Classes")
print(iris.target_names)
print()
print("Nome dos Atributos")
print(iris.feature_names)
print()

Amostra de entrada
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.

Separando o conjunto de dados em conjunto de treinamento e conjunto de teste

In [3]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=42)

print ("x train")
print(x_train)

print ("x test")
print(x_test)

print("y train")
print(y_train)

print("y test")
print(y_test)


x train
[[5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 2.4 3.8 1.1]
 [6.7 3.  5.  1.7]
 [4.9 3.1 1.5 0.2]
 [5.8 2.8 5.1 2.4]
 [5.  3.4 1.5 0.2]
 [5.  3.5 1.6 0.6]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.9 3.2 5.7 2.3]
 [6.  2.7 5.1 1.6]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.5 2.5 4.  1.3]
 [4.4 2.9 1.4 0.2]
 [4.

Treinando o modelo KNN usando o conjunto de treinamento

In [4]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

Avaliando o modelo usando o conjunto de test

In [5]:
y_pred = knn.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Acurácia do modelo:", accuracy)

Acurácia do modelo: 1.0


Efetuando previsões

In [6]:
for i in range (1000):
    new_flower = np.array([[np.random.rand() * 10, np.random.rand() * 10, np.random.rand() * 10, np.random.rand() * 10]])
    prediction = knn.predict(new_flower)
    print(i, new_flower)
    print("Espécie da flor desconhecida:", iris.target_names[prediction])
    print()
    

0 [[7.63225705 3.93730079 9.89917848 3.68051694]]
Espécie da flor desconhecida: ['virginica']

1 [[7.31925911 9.53572107 5.0013245  6.48068899]]
Espécie da flor desconhecida: ['virginica']

2 [[2.13807826 6.42032039 1.01435454 1.48799251]]
Espécie da flor desconhecida: ['setosa']

3 [[4.72411051 7.74563891 7.58295886 8.83576135]]
Espécie da flor desconhecida: ['virginica']

4 [[1.4859048  2.16324226 9.20210084 1.07105142]]
Espécie da flor desconhecida: ['virginica']

5 [[5.35014863 7.0727778  2.80707885 2.00991301]]
Espécie da flor desconhecida: ['setosa']

6 [[5.29682199 8.11026812 4.91260916 9.54051752]]
Espécie da flor desconhecida: ['virginica']

7 [[2.57610881 6.00581668 4.44943717 0.57144106]]
Espécie da flor desconhecida: ['setosa']

8 [[2.83775141 7.53563013 5.37371719 7.21186332]]
Espécie da flor desconhecida: ['virginica']

9 [[2.40360997 7.67769139 4.46970158 8.44591302]]
Espécie da flor desconhecida: ['virginica']

10 [[3.04408189 9.99448781 4.78757611 2.90235149]]
Espécie 